/*
 * EmployeesAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SesamInsight.Explore.WebApi.Client.Api;
using SesamInsight.Explore.WebApi.Client.Model;
using SesamInsight.Explore.WebApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SesamInsight.Explore.WebApi.Client.Test
{
    /// <summary>
    ///  Class for testing EmployeeDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmployeeDtoTests
    {
        // TODO uncomment below to declare an instance variable for EmployeeDto
        //private EmployeeDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EmployeeDto
            //instance = new EmployeeDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EmployeeDto
        /// </summary>
        [Test]
        public void EmployeeDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" EmployeeDto
            //Assert.IsInstanceOf(typeof(EmployeeDto), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'Age'
        /// </summary>
        [Test]
        public void AgeTest()
        {
            // TODO unit test for the property 'Age'
        }
        /// <summary>
        /// Test the property 'Experience'
        /// </summary>
        [Test]
        public void ExperienceTest()
        {
            // TODO unit test for the property 'Experience'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'WorkerType'
        /// </summary>
        [Test]
        public void WorkerTypeTest()
        {
            // TODO unit test for the property 'WorkerType'
        }
        /// <summary>
        /// Test the property 'Strength'
        /// </summary>
        [Test]
        public void StrengthTest()
        {
            // TODO unit test for the property 'Strength'
        }
        /// <summary>
        /// Test the property 'Commission'
        /// </summary>
        [Test]
        public void CommissionTest()
        {
            // TODO unit test for the property 'Commission'
        }
        /// <summary>
        /// Test the property 'Efficiency'
        /// </summary>
        [Test]
        public void EfficiencyTest()
        {
            // TODO unit test for the property 'Efficiency'
        }
        /// <summary>
        /// Test the property 'Intelligence'
        /// </summary>
        [Test]
        public void IntelligenceTest()
        {
            // TODO unit test for the property 'Intelligence'
        }
        /// <summary>
        /// Test the property 'OfficeStation'
        /// </summary>
        [Test]
        public void OfficeStationTest()
        {
            // TODO unit test for the property 'OfficeStation'
        }

    }

}
