/*
 * EmployeesAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SesamInsight.Explore.WebApi.Client.Api;
using SesamInsight.Explore.WebApi.Client.Model;
using SesamInsight.Explore.WebApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SesamInsight.Explore.WebApi.Client.Test
{
    /// <summary>
    ///  Class for testing WorkerType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkerTypeTests
    {
        // TODO uncomment below to declare an instance variable for WorkerType
        //private WorkerType instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WorkerType
            //instance = new WorkerType();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WorkerType
        /// </summary>
        [Test]
        public void WorkerTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" WorkerType
            //Assert.IsInstanceOf(typeof(WorkerType), instance);
        }



    }

}
