/*
 * EmployeesAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using SesamInsight.Explore.WebApi.Client.Client;
using SesamInsight.Explore.WebApi.Client.Api;
using SesamInsight.Explore.WebApi.Client.Model;

namespace SesamInsight.Explore.WebApi.Client.Test
{
    /// <summary>
    ///  Class for testing EmployeeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class EmployeeApiTests
    {
        private EmployeeApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new EmployeeApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EmployeeApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' EmployeeApi
            //Assert.IsInstanceOf(typeof(EmployeeApi), instance);
        }

        
        /// <summary>
        /// Test ApiEmployeeEmployeeIdDelete
        /// </summary>
        [Test]
        public void ApiEmployeeEmployeeIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid employeeId = null;
            //instance.ApiEmployeeEmployeeIdDelete(employeeId);
            
        }
        
        /// <summary>
        /// Test ApiEmployeeEmployeesByCityCityGet
        /// </summary>
        [Test]
        public void ApiEmployeeEmployeesByCityCityGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string city = null;
            //instance.ApiEmployeeEmployeesByCityCityGet(city);
            
        }
        
        /// <summary>
        /// Test ApiEmployeeEmployeesWithValueGet
        /// </summary>
        [Test]
        public void ApiEmployeeEmployeesWithValueGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiEmployeeEmployeesWithValueGet();
            //Assert.IsInstanceOf(typeof(Object), response, "response is Object");
        }
        
        /// <summary>
        /// Test ApiEmployeeEvaluateEmployeeIdGet
        /// </summary>
        [Test]
        public void ApiEmployeeEvaluateEmployeeIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid employeeId = null;
            //instance.ApiEmployeeEvaluateEmployeeIdGet(employeeId);
            
        }
        
        /// <summary>
        /// Test ApiEmployeeGet
        /// </summary>
        [Test]
        public void ApiEmployeeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiEmployeeGet();
            
        }
        
        /// <summary>
        /// Test ApiEmployeePost
        /// </summary>
        [Test]
        public void ApiEmployeePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<EmployeeDto> employeeDto = null;
            //instance.ApiEmployeePost(employeeDto);
            
        }
        
        /// <summary>
        /// Test ApiEmployeeSortedEmployeesGet
        /// </summary>
        [Test]
        public void ApiEmployeeSortedEmployeesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiEmployeeSortedEmployeesGet();
            
        }
        
    }

}
