/*
 * EmployeesAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using SesamInsight.Explore.WebApi.Client.Client;
using SesamInsight.Explore.WebApi.Client.Api;

namespace SesamInsight.Explore.WebApi.Client.Test
{
    /// <summary>
    ///  Class for testing StationsComponentApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class StationsComponentApiTests
    {
        private StationsComponentApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new StationsComponentApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StationsComponentApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' StationsComponentApi
            //Assert.IsInstanceOf(typeof(StationsComponentApi), instance);
        }

        
        /// <summary>
        /// Test ApiStationsComponentGet
        /// </summary>
        [Test]
        public void ApiStationsComponentGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiStationsComponentGet();
            
        }
        
        /// <summary>
        /// Test ApiStationsComponentSignaturePost
        /// </summary>
        [Test]
        public void ApiStationsComponentSignaturePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string signature = null;
            //instance.ApiStationsComponentSignaturePost(signature);
            
        }
        
    }

}
