/*
 * EmployeesAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SesamInsight.Explore.WebApi.Client.Client.OpenAPIDateConverter;

namespace SesamInsight.Explore.WebApi.Client.Model
{
    /// <summary>
    /// Defines WorkerType
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum WorkerType
    {
        /// <summary>
        /// Enum OfficeWorker for value: OfficeWorker
        /// </summary>
        [EnumMember(Value = "OfficeWorker")]
        OfficeWorker = 1,

        /// <summary>
        /// Enum PhysicalWorker for value: PhysicalWorker
        /// </summary>
        [EnumMember(Value = "PhysicalWorker")]
        PhysicalWorker = 2,

        /// <summary>
        /// Enum Trader for value: Trader
        /// </summary>
        [EnumMember(Value = "Trader")]
        Trader = 3

    }

}
